chore: Relax the unicode-width requirement for anstyle-svg
`anstyle-ratatui` depends on `unicode-width =0.2.0` which creates
an incompatibility

```
error: failed to select a version for `unicode-width`.
    ... required by package `ratatui v0.29.0`
    ... which satisfies dependency `ratatui = "^0.29.0"` of package `anstyle-ratatui v0.1.0 (/home/orhun/gh/anstyle/crates/anstyle-ratatui)`
versions that meet the requirements `=0.2.0` are: 0.2.0

all possible versions conflict with previously selected packages.

  previously selected package `unicode-width v0.2.2`
    ... which satisfies dependency `unicode-width = "^0.2.2"` of package `anstyle-svg v0.1.12 (/home/orhun/gh/anstyle/crates/anstyle-svg)`

failed to select a version for `unicode-width` which could resolve this conflict
```